name: "Waveshare PoE HAT (B) 2024"
description: "PoE HAT Support"
version: "1.2024.0"
slug: "poe_hat"
init: false
host_network: true
arch:
  - aarch64
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-10
  - /dev/i2c-11
options:
  fan_temp: 43
  rotate_180: false
schema:
  fan_temp: int
  rotate_180: bool
ports:
  5000/tcp: 5000
services:
  poe_hat:
    description: "PoE HAT (B) Fan and Display"
#url: "https://github.com/home-assistant/addons-example/tree/main/example"
#image: "ghcr.io/home-assistant/{arch}-addon-example"
